# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qMdhEhKH9Kp_MPvY5JgsK9aCThQsqkCH
"""

import streamlit as st
import pandas as pd
import numpy as np
import joblib
from pathlib import Path

# ---------- CONFIG ----------
st.set_page_config(page_title="Expected CTC Predictor", layout="wide")

# ---------- LOAD MODEL FILES FROM GOOGLE DRIVE ----------
import joblib, requests
import io

def load_from_url(url):
    return joblib.load(io.BytesIO(requests.get(url).content))

model = load_from_url("https://raw.githubusercontent.com/shlokshukla200/ML-Capstone_Project/main/Models/xgboost_model.pkl")
label_encoders = load_from_url("https://raw.githubusercontent.com/shlokshukla200/ML-Capstone_Project/main/Models/label_encoders.pkl")
scaler = load_from_url("https://raw.githubusercontent.com/shlokshukla200/ML-Capstone_Project/main/Models/min_max_scaler.pkl")


# ---------- FEATURE & NUMERIC COLUMN LIST ----------
FEATURES = ['Total_Experience', 'Total_Experience_in_field_applied', 'Department', 'Role', 'Industry', 'Organization', 'Designation', 'Education', 'Graduation_Specialization', 'University_Grad', 'Passing_Year_Of_Graduation', 'PG_Specialization', 'University_PG', 'Passing_Year_Of_PG', 'PHD_Specialization', 'University_PHD', 'Passing_Year_Of_PHD', 'Curent_Location', 'Preferred_location', 'Current_CTC', 'Inhand_Offer', 'Last_Appraisal_Rating', 'No_Of_Companies_worked', 'Number_of_Publications', 'Certifications', 'International_degree_any']

numeric_cols = ['Total_Experience', 'Total_Experience_in_field_applied', 'Passing_Year_Of_Graduation', 'Passing_Year_Of_PG', 'Passing_Year_Of_PHD', 'Current_CTC', 'No_Of_Companies_worked', 'Number_of_Publications', 'Certifications', 'International_degree_any']

# ---------- BASIC TECH UI AND BACKGROUND ----------
# ---------- BASIC TECH UI AND BACKGROUND ----------
st.markdown("""
<style>

/* ---------- GENERAL PAGE BACKGROUND ---------- */
.stApp {
  background-size: cover;
  background-color: #0d1117;
  background-position: center;
  background-repeat: no-repeat;
  font-family: "Brush Script MT", cursive !important;
  color: #ffffff !important;
}

/* ---------- BASE FONT STYLING ---------- */
html, body, .stApp {
  font-size: 19px !important;
  font-weight: 500 !important;
  font-family: "Brush Script MT", cursive !important;
  color: #ffffff !important;
}

/* ---------- HEADER ---------- */
.header {
  background: linear-gradient(90deg, rgba(15,23,42,0.9) 0%, rgba(14,165,233,0.8) 100%);
  padding: 18px;
  border-radius: 10px;
  color: #ffffff !important;
  text-align: center;
  font-size: 32px !important;
  font-weight: 700 !important;
  font-family: "Brush Script MT", cursive !important;
}

/* ---------- SECTION BOXES ---------- */
.section {
  background: rgba(0, 0, 0, 0.45);
  border-radius: 12px;
  padding: 22px;
  box-shadow: 0 4px 15px rgba(255,255,255,0.1);
  margin-bottom: 20px;
  color: #ffffff !important;
}

/* ---------- HEADINGS ---------- */
h1, h2, h3, h4, h5 {
  font-family: "Brush Script MT", cursive !important;
  font-weight: 700 !important;
  color: #ffffff !important;
}

/* ---------- LABELS & TEXT ---------- */
label, p, div, span, input, select {
  font-family: "Brush Script MT", cursive !important;
  font-size: 19px !important;
  color: #ffffff !important;
}

/* ---------- BUTTONS ---------- */
div.stButton > button:first-child {
  background: linear-gradient(90deg, #3b82f6, #0ea5e9);
  color: #ffffff !important;
  border: none;
  border-radius: 10px;
  padding: 10px 25px;
  font-size: 20px !important;
  font-weight: 700 !important;
  transition: 0.3s ease;
  box-shadow: 0 0 10px rgba(14,165,233,0.6);
}
div.stButton > button:first-child:hover {
  background: linear-gradient(90deg, #60a5fa, #1e3a8a);
  transform: scale(1.05);
  box-shadow: 0 0 15px rgba(14,165,233,0.8);
}

/* ---------- SUCCESS (Predicted CTC) ---------- */
.stSuccess {
  font-size: 24px !important;
  font-weight: 800 !important;
  color: #ffffff !important;
  background: rgba(14,165,233,0.25);
  border-radius: 10px;
  padding: 12px;
  text-shadow: 1px 1px 3px rgba(0,0,0,0.4);
}

/* ---------- FOOTER ---------- */
small {
  font-size: 17px !important;
  font-weight: 600 !important;
  color: #ffffff !important;
}
</style>
""", unsafe_allow_html=True)




st.markdown('<div class="header"><h1>ML-Powered Expected CTC Predictor</h1></div>', unsafe_allow_html=True)

tabs = st.tabs(["Profile", "Job", "Education", "Performance", "Predict"])

# ---------- TAB 1: PROFILE ----------
with tabs[0]:
    st.markdown('<div class="section">', unsafe_allow_html=True)
    st.subheader("Profile & Experience")
    total_exp = st.number_input("Total Experience (Years)", 0.0, 60.0, 3.0, step=1.0)
    field_exp = st.number_input("Experience in Applied Field (Years)", 0.0, 60.0, 2.0, step=1.0)
    current_ctc = st.number_input("Current CTC (LPA)", 0.0, 200.0, 6.0, step=0.5)
    inhand_offer = st.number_input("In-hand Offer (LPA)", 0.0, 200.0, 0.0, step=0.5)
    st.markdown('</div>', unsafe_allow_html=True)

# ---------- TAB 2: JOB ----------
with tabs[1]:
    st.markdown('<div class="section">', unsafe_allow_html=True)
    st.subheader("Job & Industry Details")
    def select_cat(col): return st.selectbox(col, label_encoders[col].classes_) if col in label_encoders else st.text_input(col)
    department = select_cat('Department')
    role = select_cat('Role')
    industry = select_cat('Industry')
    organization = select_cat('Organization')
    designation = select_cat('Designation')
    curent_location = select_cat('Curent_Location')
    major_indian_cities = [
        "Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad",
        "Pune", "Ahmedabad", "Surat", "Jaipur", "Lucknow", "Kanpur",
        "Nagpur", "Visakhapatnam", "Indore", "Bhopal", "Patna", "Vadodara",
        "Ghaziabad", "Ludhiana", "Agra", "Nashik", "Faridabad", "Meerut",
        "Rajkot", "Kalyan-Dombivli", "Vasai-Virar", "Varanasi", "Srinagar",
        "Aurangabad", "Dhanbad", "Amritsar", "Navi Mumbai", "Allahabad",
        "Howrah", "Gwalior", "Jabalpur", "Coimbatore", "Vijayawada", "Jodhpur",
        "Madurai", "Raipur", "Kota", "Guwahati", "Chandigarh", "Thiruvananthapuram",
        "Mysore", "Tiruchirappalli", "Bhubaneswar", "Salem", "Warangal", "Guntur",
        "Bhiwandi", "Saharanpur", "Gorakhpur", "Bikaner", "Amravati", "Noida",
        "Jamshedpur", "Bhilai", "Cuttack", "Firozabad", "Nanded", "Kolhapur",
        "Ajmer", "Akola", "Gulbarga", "Jamnagar", "Ujjain", "Loni", "Siliguri",
        "Jhansi", "Ulhasnagar", "Nellore", "Jammu", "Mirzapur", "Sangli-Miraj & Kupwad",
        "Bhavnagar", "Parbhani", "Malegaon", "Erode", "Dholpur", "Moradabad",
        "Bareilly", "Jalgaon", "Kurnool", "Rajahmundry", "Tirunelveli", "Darbhanga",
        "Ichalkaranji", "Ongole", "Port Blair"
    ]
    preferred_location = st.selectbox("Preferred Location", major_indian_cities) # Changed to selectbox    st.markdown('</div>', unsafe_allow_html=True)

# ---------- TAB 3: EDUCATION ----------
with tabs[2]:
    st.markdown('<div class="section">', unsafe_allow_html=True)
    st.subheader("Education Details")
    education = select_cat('Education')
    grad_spec = select_cat('Graduation_Specialization')
    pg_spec = select_cat('PG_Specialization')
    phd_spec = select_cat('PHD_Specialization')
    grad_univ = select_cat('University_Grad')
    pg_univ = select_cat('University_PG')
    phd_univ = select_cat('University_PHD')
    pass_grad = st.number_input("Passing Year of Graduation", 1970, 2035, 2018, step=1)
    pass_pg = st.number_input("Passing Year of PG", 1970, 2035, 2000, step=1)
    pass_phd = st.number_input("Passing Year of PhD", 1970, 2035, 2000, step=1)
    st.markdown('</div>', unsafe_allow_html=True)


# ---------- TAB 4: PERFORMANCE ----------
with tabs[3]:
    st.markdown('<div class="section">', unsafe_allow_html=True)
    st.subheader("Performance & Certifications")
    certs = st.number_input("Certifications", 0, 50, 0)
    intl_deg = st.selectbox("International Degree?", ["No","Yes"])
    rating = select_cat('Last_Appraisal_Rating')
    no_of_companies = st.number_input("Number of Companies Worked", 0, 20, 1) # Added back
    num_publications = st.number_input("Number of Publications", 0, 50, 0) # Added back
    st.markdown('</div>', unsafe_allow_html=True)

# ---------- TAB 5: PREDICT ----------
with tabs[4]:
    st.markdown('<div class="section">', unsafe_allow_html=True)
    st.subheader("Predict Expected CTC")

    if st.button("✨ Predict Expected CTC"):
      input_dict = {
            'Department': department,'Role': role,'Industry': industry,
            'Organization': organization,'Designation': designation,
            'Education': education,'Graduation_Specialization': grad_spec,
            'PG_Specialization': pg_spec,'PHD_Specialization': phd_spec,
            'University_Grad': grad_univ,'University_PG': pg_univ,'University_PHD': phd_univ,
            'Passing_Year_Of_Graduation': pass_grad,'Passing_Year_Of_PG': pass_pg,'Passing_Year_Of_PHD': pass_phd,
            'Total_Experience': total_exp,'Total_Experience_in_field_applied': field_exp,
            'Current_CTC': current_ctc,'Inhand_Offer': inhand_offer,
            'Certifications': certs,'International_degree_any': 1 if intl_deg=="Yes" else 0,
            'Last_Appraisal_Rating': rating,
            'Curent_Location': curent_location,
            'No_Of_Companies_worked': no_of_companies,
            'Number_of_Publications': num_publications,
            'Preferred_location': preferred_location
      }
      X = pd.DataFrame([input_dict])

      # Add missing columns if any
      for col in FEATURES:
          if col not in X.columns:
              if col in numeric_cols:
                  X[col] = 0.0
              else:
                  X[col] = 'Missing' # Or a suitable default category

      # Ensure columns are in the correct order
      X = X[FEATURES]

      # Encode categorical safely
      for col, le in label_encoders.items():
        if col in X.columns:
          try:
            X[col] = le.transform(X[col].astype(str))
          except ValueError:
            known_classes = list(le.classes_)
            val = str(X.at[0, col])
            if val.isdigit() and int(val) in known_classes:
              X[col] = le.transform([val])
            else:
              default_class = known_classes[0]
              X[col] = le.transform([default_class])

      # Convert numeric columns
      for col in numeric_cols:
          X[col] = pd.to_numeric(X[col], errors='coerce').fillna(0.0)

      # Identify all columns that are now numeric (original numeric + encoded categorical)
      all_numeric_cols_after_encoding = X.select_dtypes(include=np.number).columns.tolist()

      # Scale all numeric columns
      X[all_numeric_cols_after_encoding] = scaler.transform(X[all_numeric_cols_after_encoding])

      pred = model.predict(X)[0]
      st.success(f"💰 Predicted Expected CTC: ₹ {pred:,.2f}")
    st.markdown('</div>', unsafe_allow_html=True)

st.markdown("<center><small>Developed by Shlok Shukla</small></center>", unsafe_allow_html=True)